### ISSUE TITLE
Have our documentation deployed to GitHub Pages

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#172]
It would be nice to have our documentation deployed to GitHub pages, which is live up-to-date with main. Additionally it would also be nice to have a documentation preview for pull-requests.

* An initial attempt at this was completed, but it appears we do not yet have enough permissions of the repository to correctly administer this.

I had created a simple CI script that tried to deploy the docs : here is the file. Perhaps this might be useful for a future solution.

```yaml
name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install prerequisites
        run: python3 -m pip install -r third_party/requirements.txt

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build Documentation
        working-directory: ${{github.workspace}}/scripts
        run: python3 run.py --core
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{github.workspace}}/docs/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
