### ISSUE TITLE
Allow for platform dependant type defintions

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#704]
Currently in UR we have do not have a mechanism to define types diferently for different platforms i.e. Windows/Linux. This is something that would be helpful in implementing for example a file descriptor type which differs across platforms and would be important to implement bindless images experimental features. See discussion [here](https://github.com/oneapi-src/unified-runtime/blob/main/scripts/core/common.yml#L39)
We can do something similar with macros currently using a `condition: "defined(_WIN32)"` field in the `yaml` syntax which will include an additional gaurd for the definition, however the is nothing for other yaml types. The most obvious place would be to add this to `typedef` which would allow us to define types differently for different platforms - a potential way this could look would be:

```yaml
type: typedef
desc: "file descriptor type:
name: $x_file_descriptor_t
value:
  - condition: "defined(_WIN32)"
    value: HANDLE
alt_value: int
```

**Comment by kbenzie** [comment]
I think something like this would be more flexible:

```yaml
type: typedef
desc: "file descriptor type:"
name: $x_file_descriptor_t
value:
  - if: "defined(_WIN32)"
    value: HANDLE
  - elif: "defined(OTHER_PLATFORM)"
    value: other_platform_t
  - else:
    value: int
```
