### ISSUE TITLE
Support raw C-style array type in spec-generator

### ISSUE THREAD

**Issue by veselypeta** [oneapi-src/unified-runtime#869]
Currently the following syntax will fail to generate the spec if a c-style raw array is used in a struct type definition 
i.e.

```yml
type: size_t
name: my_array[3]
desc: [in] C-Style array

```

**Comment by kbenzie** [comment]
I don't think the array specifier should be part of the name but rather the type:

```yaml
type: size_t[3]
name: my_array
desc: [in] C-Style array
```
